global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "clash"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["clash-exporter:2112"]

rule_files:
  - "/etc/prometheus/record.rules.yml"
